name: freenginx Mega Build
run-name: freenginx Build
on:
  push:
    tags:        
      - freenginx-*
jobs:
  build_nginx:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up environment variables
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          NGINX_TAG=${TAG_NAME#freenginx-}
          
          echo "NGINX_TAG=${NGINX_TAG}" >> $GITHUB_ENV
          echo "NGINX_TAG=${NGINX_TAG}"
          
      - name: Run freenginx Build (Vanilla)
        run: |
          echo "This Task will be run using the following tag: ${NGINX_TAG}"
          curl https://raw.githubusercontent.com/minoplhy/scriptbox/main/nginx_build_script/build.sh | bash -s -- --nginx-tag=${NGINX_TAG} --no-lua --no-modsecurity --type=freenginx
          tar czvf nginx-${NGINX_TAG}-vanilla.tar.gz ~/nginx_scriptbox/nginx/objs

      - name: Run freenginx Build (All Star)
        run: |
          echo "This Task will be run using the following tag: ${NGINX_TAG}"
          curl https://raw.githubusercontent.com/minoplhy/scriptbox/main/nginx_build_script/build.sh | bash -s -- --nginx-tag=${NGINX_TAG} --type=freenginx
          tar czvf nginx-${NGINX_TAG}-allstar.tar.gz ~/nginx_scriptbox/nginx/objs /opt/nginx-lua-module /usr/local/lua /usr/local/modsecurity
        
      - name: Run freenginx Build (Lua)
        run: |
          echo "This Task will be run using the following tag: ${NGINX_TAG}"
          curl https://raw.githubusercontent.com/minoplhy/scriptbox/main/nginx_build_script/build.sh | bash -s -- --nginx-tag=${NGINX_TAG} --no-modsecurity --type=freenginx
          tar czvf nginx-${NGINX_TAG}-lua.tar.gz ~/nginx_scriptbox/nginx/objs /opt/nginx-lua-module /usr/local/lua

      - name: Run freenginx Build (ModSecurity)
        run: |
          echo "This Task will be run using the following tag: ${NGINX_TAG}"
          curl https://raw.githubusercontent.com/minoplhy/scriptbox/main/nginx_build_script/build.sh | bash -s -- --nginx-tag=${NGINX_TAG} --no-lua --type=freenginx
          tar czvf nginx-${NGINX_TAG}-modsecurity.tar.gz ~/nginx_scriptbox/nginx/objs /usr/local/modsecurity
          
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: |
            "freenginx Successfully build on -> ${{ env.NGINX_TAG }}"
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
          files: nginx-*.tar.gz
