name: Nginx Mega Build
run-name: Nginx Build
on:
  push:
    tags:        
      - nginx-*
jobs:
  build_nginx:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up environment variables
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          NGINX_TAG=${TAG_NAME#nginx-}
          
          echo "NGINX_TAG=${NGINX_TAG}" >> $GITHUB_ENV
          echo "NGINX_TAG=${NGINX_TAG}"
          
      - name: Run Nginx Build (Vanilla)
        run: |
          echo "This Task will be run using the following tag: ${NGINX_TAG}"
          curl https://raw.githubusercontent.com/minoplhy/scriptbox/main/nginx_build_script/build.sh | bash -s -- --nginx-tag=${NGINX_TAG} -nl -nm
          tar czvf nginx-${NGINX_TAG}-vanilla.tar.gz ~/nginx_scriptbox/nginx/objs

      - name: Run Nginx Build (All Star)
        run: |
          echo "This Task will be run using the following tag: ${NGINX_TAG}"
          curl https://raw.githubusercontent.com/minoplhy/scriptbox/main/nginx_build_script/build.sh | bash -s -- --nginx-tag=${NGINX_TAG}
          tar czvf nginx-${NGINX_TAG}-allstar.tar.gz ~/nginx_scriptbox/nginx/objs /var/lib/modsecurity /opt/nginx-lua-module /usr/local/lua
          
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: |
            "Nginx Successfully build on -> ${{ env.NGINX_TAG }}"
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
          files: nginx-*.tar.gz
